# This docker-compose can be used to run this service in standalone mode, i.e. on its own, isolated

#														#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>	#
#														#

version: "3"
services:
    registry:
        image: identifiersorg/cloud-ws-registry
        environment:
            - WS_REGISTRY_CONFIG_RESOLVER_HOST=resolver
            - WS_REGISTRY_CONFIG_RESOLVER_PORT=8080
            - WS_REGISTRY_CONFIG_EMAIL_HOST=set_your_environment_value
            - WS_REGISTRY_CONFIG_EMAIL_PORT=set_your_environment_value
            - WS_REGISTRY_CONFIG_EMAIL_USERNAME=set_your_environment_value
            - WS_REGISTRY_CONFIG_EMAIL_PASSWORD=set_your_environment_value
            - WS_REGISTRY_CONFIG_EMAIL_TRANSPORT_PROTOCOL=set_your_environment_value
            - WS_REGISTRY_CONFIG_EMAIL_BOOLEAN_SMTP_AUTH=set_your_environment_value
            - WS_REGISTRY_CONFIG_EMAIL_BOOLEAN_START_TLS=set_your_environment_value
            - WS_REGISTRY_CONFIG_EMAIL_BOOLEAN_DEBUG=set_your_environment_value
            - WS_REGISTRY_CONFIG_EMAIL_FROM=set_your_environment_value
        ports:
            - 8081:8081
        depends_on:
            - resolver
    resolver:
        image: identifiersorg/cloud-ws-resolver
        environment:
            - WS_RESOLVER_CONFIG_REDIS_HOST=redis
            - WS_RESOLVER_CONFIG_REDIS_PORT=6379
        ports:
            - 8080:8080
        depends_on:
            - redis
    redis:
        image: redis
        ports:
            - 6379:6379
