# This docker-compose file defines the development environment

#														#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>	#
#														#

version: "3"
services:
    resolver:
        image: identifiersorg/cloud-ws-resolver
        ports:
            - 8080:8080
    httpstatus:
        image: identifiersorg/cloud-ws-httpstatus
        ports:
            - 8079:8079
