# This docker-compose file defines the development environment

#														#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>	#
#														#

version: "3"
services:
    resolver:
        image: identifiersorg/cloud-ws-resolver
        environment:
            - WS_RESOLVER_CONFIG_REDIS_HOST=redis
            - WS_RESOLVER_CONFIG_REDIS_PORT=6379
        ports:
            - 8080:8080
        depends_on:
            - redis
    redis:
        image: redis
        ports:
            - 6379:6379
    httpstatus:
        image: identifiersorg/cloud-ws-httpstatus
        ports:
            - 8079:8079
