# This docker-compose file defines the development environment

#														#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>	#
#														#

version: "3"
services:
    resolver:
        image: identifiersorg/cloud-ws-resolver
        environment:
            - WS_RESOLVER_CONFIG_REDIS_HOST=redis
            - WS_RESOLVER_CONFIG_REDIS_PORT=6379
            - WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_HOST=recommender
            - WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_PORT=8083
            - WS_RESOLVER_JVM_MEMORY_MAX=1024m
        ports:
            - "8080:8080"
        depends_on:
            - redis
            - recommender
    redis:
        image: redis:4.0.8-alpine
        ports:
            - "6379:6379"
    recommender:
        image: identifiersorg/cloud-ws-resource-recommender
        environment:
            - WS_RESOURCE_RECOMMENDER_JVM_MEMORY_MAX=1024m
        ports:
            - "8083:8083"
    httpstatus:
        image: identifiersorg/cloud-ws-httpstatus
        ports:
            - "8079:8079"
    fakesmtp:
        image: digiplant/fake-smtp
        ports:
            - "1025:25"
        volumes:
            - ./tmp/fakesmtp:/var/mail
